import { PropsWithChildren } from 'react';
import type { Metadata, Viewport } from 'next';
import { NextIntlClientProvider, useLocale } from 'next-intl';
import { ThemeProvider } from 'next-themes';

import './globals.css';

export const metadata: Metadata = {
	title: 'N',
	description: 'Generated by create next app',
};

export const viewport: Viewport = {
	width: 'device-width',
	initialScale: 1,
	maximumScale: 1,
	viewportFit: 'cover',
	userScalable: false,
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
	const lang = useLocale();
	return (
		<html lang={lang} suppressHydrationWarning className='h-full w-full'>
			<body className='h-full w-full overflow-hidden'>
				<ThemeProvider
					defaultTheme='system'
					attribute='data-theme'
					storageKey='nextadm-theme'
					enableSystem
					enableColorScheme={false}
					disableTransitionOnChange
				>
					<NextIntlClientProvider>{children}</NextIntlClientProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
