// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/qhai-dev/panda/admin/internal/application"
	"github.com/qhai-dev/panda/admin/internal/application/command"
	"github.com/qhai-dev/panda/admin/internal/infra"
	"github.com/qhai-dev/panda/admin/internal/infra/conf"
	"github.com/qhai-dev/panda/admin/internal/infra/repository"
	"github.com/qhai-dev/panda/admin/internal/interface/rest"
	"github.com/qhai-dev/panda/admin/internal/interface/rest/handler"
	"github.com/qhai-dev/panda/pkg/database"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	config := conf.Load()
	logger := infra.NewLogger(config)
	db, err := database.NewDatabase()
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	loginHandler := command.NewLoginHandler(userRepository, logger)
	loginService := application.ProvideLoginService(loginHandler)
	handlerLoginHandler := handler.NewLoginHandler(loginService)
	apiHandler := handler.NewAPIHandler(handlerLoginHandler)
	engine := rest.NewRouter(apiHandler, logger)
	server := rest.NewServer(config, logger, engine)
	app := NewApp(server)
	return app, nil
}

// wire.go:

type App struct {
	RestServer *rest.Server
}

func NewApp(
	restServer *rest.Server,
) *App {
	return &App{
		RestServer: restServer,
	}
}
