package entity

import "time"

type Enterprise struct {
	ID        int64     // 企业ID
	Name      string    // 企业名称
	Avator    string    // 企业头像
	Status    bool      // 企业状态
	OwnerID   int64     // 企业联系人ID
	UpdatedBy int64     // 更新人ID
	CreatedAt time.Time // 创建时间
	UpdatedAt time.Time // 更新时间
}

/**
* 创建企业 需要的字段
* 1. 企业名称
* 2. 企业用户
* 2.1 用户的类型 owner admin 普通用户

CREATE TABLE enterprises (
    id          BIGSERIAL PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    status      VARCHAR(32) NOT NULL DEFAULT 'active',
    owner_id    BIGINT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at  TIMESTAMPTZ NULL
);
functionalRole

https://ai6bxh78u4z.feishu.cn/suite/admin/functionalRole/?_t=1774175190374

https://ai6bxh78u4z.feishu.cn/suite/admin/role/v3/controllable?offset=0&limit=20&_t=1774175190327
{
    "roles": [
        {
            "administrators": [
                {
                    "avatar": "https://s3-imfile.feishucdn.com/static-resource/v1/v3_009c_711edc76-5c1e-488f-a101-74309de72e7g~?image_size=&cut_type=&quality=&format=&sticker_format=.webp",
                    "depts": [
                        "个人团队"
                    ],
                    "id": "7350921621005484060",
                    "mobile": "+8618338625417",
                    "name": "清海",
                    "type": 3
                }
            ],
            "canEdit": true,
            "deniedPermissions": [
                "Static_FeishuCoreHRConfiguration",
                "-84"
            ],
            "hasChild": false,
            "id": "7350919546861469724",
            "name": "超级管理员",
            "parentID": "0",
            "pathNode": [
                {
                    "id": "7350919546861469724",
                    "name": "Suite_Admin_Role_Name_Super",
                    "parentID": "0"
                }
            ],
            "permissions": [
                "Static_Organization",
                "-2",
                "-83",
                "viewMembDept",
                "editMembTab",
                "addMemb",
                "inviteMemb",
                "batchImportExportMemb",
                "inactiveMembReminder",
                "changeMembDepartment",
                "batchDeleteMemb",
                "suspendAccount",
                "transferResource",
                "membList",
                "editMembInfo",
                "resetLoginPassword",
                "editLoginCredential",
                "editDeptTab",
                "newDept",
                "batchImportExportDept",
                "editDeptInfo",
                "deleteBatchDeleteDept",
                "deletedMembTab",
                "viewDeletedMemb",
                "editDeletedMembTab",
                "deleteDeletedMembr",
                "restoreDeletedMembr",
                "updateDeletedMembInfo",
                "Static_RoleManagement",
                "Static_UnitManagement",
                "-35",
                "userGroupRead",
                "userGroupAction",
                "mgmGroupSet",
                "addGroupSet",
                "editGroupSet",
                "delGroupSet",
                "addUserGroup",
                "editUserGroup",
                "delUserGroup",
                "batIEUserGroup",
                "addUserGroupMem",
                "displayAllMems",
                "remDeptOrMemUG",
                "dynGroupRead",
                "dynGroupAction",
                "mgmDynGroupSet",
                "addDynGroupSet",
                "editDynGroupSet",
                "delDynGroupSet",
                "addDynGroup",
                "editDynGroup",
                "delDynGroup",
                "viewDynGroupMems",
                "Static_FieldManagement",
                "Related_Organization",
                "Related_OrganizationList",
                "extContacts",
                "Related_OrganizationGlobalSetting",
                "Related_OrganizationApplication",
                "-15",
                "-4",
                "-6",
                "appTestTenant",
                "workplaceSet",
                "Static_CustomWorkplace",
                "-10",
                "aiUsageMgm",
                "usageOverview",
                "usageDetail",
                "usageLogs",
                "quotaMgm",
                "aiUseData",
                "storage",
                "storageCleaning",
                "storageUsage",
                "storageLimits",
                "-21",
                "Statistic_ReportOverview",
                "-22",
                "Statistic_ReportUserActivityOverview",
                "Statistic_ReportUserActivityDetail",
                "-36",
                "-23",
                "-24",
                "-25",
                "-26",
                "Statistic_ReportEmail",
                "Statistic_ReportTask",
                "-27",
                "-28",
                "-19",
                "brandSettings",
                "brandDisplay",
                "contactUs",
                "aboutPage",
                "installationGuideDisplay",
                "assistantNotificationSettings",
                "featureSettings",
                "navigationBar",
                "mobileOpenPage",
                "appThemeSettings",
                "organizationEmojis",
                "badges",
                "organizationRedpacket",
                "messengerTextInput",
                "docSettings",
                "Static_AppAvailability",
                "-79",
                "-80",
                "-81",
                "-82",
                "-1",
                "Static_companyInfoManage",
                "Static_companyAddrManage",
                "Static_peopleAuthorization",
                "Static_RiskControl",
                "Static_SensitiveOperationProtection",
                "Static_ConfidentialMemberProtection",
                "Static_DataMigration",
                "Static_SlackMigration",
                "Static_ExchangeCalendarMigration",
                "Static_GoogleCalendarMigration",
                "Static_GoogleDriveMigration",
                "Static_ConfluenceMigration",
                "Static_YuQueMigration",
                "Static_QuipMigration",
                "Static_DingTalkDiskMigration",
                "Static_OneDriveMigration",
                "Static_VDiskMigration",
                "Static_ShiMoMigration",
                "dirSyncSCIM",
                "Static_VersionManagement",
                "securityCenter",
                "userAlert",
                "docAlert",
                "policyCenter",
                "networkFence",
                "deviceMgt",
                "contentMatRule",
                "detector",
                "policyMgt",
                "Security_ScsAuditLogAlarm",
                "Security_UserPermissions",
                "Security_OrgVisibility",
                "Security_ProfileVisibility",
                "Security_SearchAuth",
                "Security_CommunicateAuth",
                "Security_ExternalCommuni",
                "Security_SecureChat",
                "Security_DocsSettings",
                "Security_DocsActionPermit",
                "Security_DocsPermDefault",
                "docsAccess",
                "basespaceSet",
                "permDispoPolicy",
                "-31",
                "-75",
                "Security_SSOAccountManage",
                "-76",
                "Security_LoginPasswordManage",
                "Security_TwoStepVerifi",
                "Security_LoginValidPeriod",
                "Security_MultiterminalLogin",
                "-77",
                "-66",
                "Security_LoginPolicyManage",
                "Security_FilePolicyManage",
                "-73",
                "Security_DeviceManage",
                "Security_MobilDocsEncrypt",
                "Security_PasteProtection",
                "-89",
                "Security_FileSecurityDetect",
                "tenantsRestrict",
                "datawipe",
                "Security_GeneralSettings",
                "Security_FenceManagement",
                "intranet",
                "URLSecurity",
                "Security_DataClassification",
                "Security_DataDiscovery",
                "Security_DataDiscoveryLog",
                "Security_SensitiveInfoType",
                "Security_FileFingerPrint",
                "-32",
                "Security_SecureLabels",
                "Security_AutoRecordPolicyLog",
                "Security_Watermarks",
                "Security_SensitiveWords",
                "Security_FeishuDLP",
                "-74",
                "Security_SkyGuardDLP",
                "Security_SkyGuardDLPPolicyLog",
                "Security_MyAIDLP",
                "Security_MyAIDLPLog",
                "Security_DeploymentAndEncryption",
                "Security_BYOK",
                "Security_ThirdPartyKeys",
                "-41",
                "encryptDecrypt",
                "-69",
                "-40",
                "lifecycleManage",
                "-65",
                "-33",
                "-8",
                "-72",
                "peopleAuditing",
                "resourceXferLog",
                "kmsEncAuditLog",
                "Security_PermAuditNew",
                "Security_RealTimeSearchpermission",
                "Security_CreateSearchPermission",
                "Security_MemberPermissionChangeHistory",
                "Security_PermissionRulesChangeHistory",
                "Security_StatusChangeNotice",
                "-42",
                "-37",
                "-70",
                "-71",
                "searchAndPreview",
                "holdManagement",
                "exportManagement",
                "exportDownload",
                "-67",
                "-45",
                "-43",
                "Security_ContentSecurity",
                "Security_AuditPolicyConfiguration",
                "Security_CustomList",
                "Security_AuditLogQuery",
                "Security_FeedbackProcess",
                "-78",
                "Security_PrivacySettings",
                "Security_SetGeoLocationInfo",
                "Static_PrivacyNotice",
                "pushManagement",
                "-16",
                "mailLFStorage",
                "serviceManagement",
                "accountManagement",
                "mailGroup",
                "sharedMail",
                "groupMail",
                "mailRecycleBin",
                "mailTools",
                "useFunction",
                "businessSignature",
                "businessFooter",
                "mailSendReceiveRecords",
                "mailDataManagement",
                "safetyRules",
                "mailBlackList",
                "mailWhiteList",
                "mailAntiSpam",
                "dkimAuth",
                "externalMailWarning",
                "dataProtection",
                "mailFlowRule",
                "Mail_ManageQuarantine",
                "Mail_AllManageQuarantineEmail",
                "Mail_PartManageQuarantineEmail",
                "spamQuarantineArea",
                "dataCompliance",
                "mailHost",
                "mailRouting",
                "-12",
                "-60",
                "upcomingMeetings",
                "otherMeetings",
                "meetingUsage",
                "usageLog",
                "management",
                "-61",
                "notesManagement",
                "-62",
                "-63",
                "Static_MediaNode",
                "Static_AreaManagement",
                "Static_StreamManagement",
                "-64",
                "-68",
                "vcPermission",
                "-39",
                "-14",
                "-44",
                "newSuperGroup",
                "groupSizeControl",
                "groupPermissions",
                "messagePermissions",
                "wallpaper",
                "groupManagement",
                "Static_Docs",
                "-18",
                "-17",
                "-29",
                "-3",
                "Static_CalendarAllStaff",
                "Static_CalendarPermissionSetting",
                "Static_CalendarEventsSetting",
                "eventManagement",
                "-20",
                "-13",
                "-86",
                "base",
                "basespaceAdmin",
                "baseRobotPerm",
                "baseWKFUsage",
                "baseAutoManage",
                "baseRowsManage",
                "baseExtension",
                "knowledgeAI",
                "-85",
                "-87",
                "Static_ESOP",
                "Static_Approval",
                "Static_Lingo",
                "-34",
                "-38",
                "Static_Ocean"
            ],
            "roleTag": 1
        },
        {
            "administrators": [
                {
                    "avatar": "https://s3-imfile.feishucdn.com/static-resource/v1/v3_009c_711edc76-5c1e-488f-a101-74309de72e7g~?image_size=&cut_type=&quality=&format=&sticker_format=.webp",
                    "depts": [
                        "个人团队"
                    ],
                    "id": "7350921621005484060",
                    "mobile": "+8618338625417",
                    "name": "清海",
                    "type": 3
                }
            ],
            "canEdit": true,
            "hasChild": false,
            "id": "7350916889093980162",
            "name": "人事管理员",
            "parentID": "0",
            "pathNode": [
                {
                    "id": "7350916889093980162",
                    "name": "Suite_Admin_AdminRoles_CoreHR",
                    "parentID": "0"
                }
            ],
            "permissions": [
                "-83",
                "Static_FeishuCoreHRConfiguration",
                "-84"
            ],
            "roleTag": 3
        },
        {
            "canEdit": true,
            "hasChild": false,
            "id": "7620056702058269902",
            "name": "管理员角色1号",
            "parentID": "0",
            "pathNode": [
                {
                    "id": "7620056702058269902",
                    "name": "管理员角色1号",
                    "parentID": "0"
                }
            ],
            "permissions": [
                "Static_Organization",
                "-2",
                "viewMembDept",
                "editMembTab",
                "addMemb",
                "inviteMemb",
                "batchImportExportMemb",
                "inactiveMembReminder",
                "changeMembDepartment",
                "batchDeleteMemb",
                "suspendAccount",
                "transferResource",
                "membList",
                "editMembInfo",
                "resetLoginPassword",
                "editLoginCredential",
                "editDeptTab",
                "newDept",
                "batchImportExportDept",
                "editDeptInfo",
                "deleteBatchDeleteDept",
                "Static_RoleManagement",
                "Static_UnitManagement",
                "-35",
                "userGroupRead",
                "userGroupAction",
                "mgmGroupSet",
                "addGroupSet",
                "editGroupSet",
                "delGroupSet",
                "addUserGroup",
                "editUserGroup",
                "delUserGroup",
                "batIEUserGroup",
                "addUserGroupMem",
                "displayAllMems",
                "remDeptOrMemUG",
                "dynGroupRead",
                "dynGroupAction",
                "mgmDynGroupSet",
                "addDynGroupSet",
                "editDynGroupSet",
                "delDynGroupSet",
                "addDynGroup",
                "editDynGroup",
                "delDynGroup",
                "viewDynGroupMems",
                "Static_FieldManagement",
                "Related_Organization",
                "Related_OrganizationList",
                "extContacts",
                "Related_OrganizationGlobalSetting",
                "Related_OrganizationApplication"
            ],
            "roleTag": 4
        }
    ],
    "total": 3
}
*/
